<?php

const WIN_GAME = 100;

const MAX_POINT = 20;
const START_LIFE = 10;

/*
 * State constants
 */
const ST_BGA_GAME_SETUP = 1;

const ST_START = 10;
const ST_PLAYER_PICK_MONSTER = 11;
const ST_PICK_MONSTER_NEXT_PLAYER = 12;

const ST_MULTIPLAYER_PICK_EVOLUTION_DECK = 13;
const ST_NEXT_PICK_EVOLUTION_DECK = 14;

const ST_PLAYER_CHOOSE_INITIAL_CARD = 15;
const ST_CHOOSE_INITIAL_CARD_NEXT_PLAYER = 16;


const ST_START_GAME = 19;

const ST_PLAYER_BEFORE_START_TURN = 25; // !
const ST_QUESTIONS_BEFORE_START_TURN = 26; // !
const ST_START_TURN = 20;
const ST_PLAYER_CHANGE_MIMICKED_CARD = 21;
const ST_MULTIPLAYER_GIVE_SYMBOL_TO_ACTIVE_PLAYER = 17; // !
const ST_INITIAL_DICE_ROLL = 18; // !
const ST_PLAYER_THROW_DICE = 22;
const ST_PLAYER_CHANGE_DIE = 23;
const ST_MULTIPLAYER_CHANGE_ACTIVE_PLAYER_DIE = 24;

const ST_PREPARE_RESOLVE_DICE = 28;
const ST_MULTIPLAYER_CHEERLEADER_SUPPORT = 29;
const ST_MULTIPLAYER_ASK_MINDBUG = 74; // !
const ST_RESOLVE_DICE = 30;
const ST_PLAYER_BEFORE_RESOLVE_DICE = 27; // !
const ST_PLAYER_BEFORE_RESOLVE_DICE_MULTI = 82; // !
const ST_RESOLVE_NUMBER_DICE = 31;
const ST_RESOLVE_HEART_DICE = 32;
const ST_RESOLVE_HEART_DICE_ACTION = 33;
const ST_RESOLVE_ENERGY_DICE = 34;
const ST_RESOLVE_SMASH_DICE = 35;
const ST_RESOLVE_SMASH_DICE_ACTION = 73; // !
const ST_RESOLVE_SKULL_DICE = 36;
const ST_RESOLVE_DIE_OF_FATE = 37;
const ST_CHOOSE_EVOLUTION_CARD = 39; // !

const ST_MULTIPLAYER_CANCEL_DAMAGE = 38;
const ST_AFTER_RESOLVE_DAMAGE = 68; // !

const ST_MULTIPLAYER_LEAVE_TOKYO = 40;
const ST_LEAVE_TOKYO_APPLY_JETS = 41;
const ST_MULTIPLAYER_LEAVE_TOKYO_EXCHANGE_CARD = 42;
const ST_MULTIPLAYER_BEFORE_ENTERING_TOKYO = 43;
const ST_ENTER_TOKYO_APPLY_BURROWING = 45;
const ST_ENTER_TOKYO = 46;
const ST_PLAYER_AFTER_ENTERING_TOKYO = 47;

const ST_PLAYER_STEAL_COSTUME_CARD_OR_GIVE_GIFT_EVOLUTION = 49;
const ST_PLAYER_CHANGE_FORM = 48; // !

const ST_PLAYER_BUY_CARD = 50;
//const ST_PLAYER_CHOOSE_MIMICKED_CARD = 51;
const ST_MULTIPLAYER_OPPORTUNIST_BUY_CARD = 52;
//const ST_MULTIPLAYER_OPPORTUNIST_CHOOSE_MIMICKED_CARD = 53;
const ST_MULTIPLAYER_WHEN_CARD_IS_BOUGHT = 54;
const ST_AFTER_WHEN_CARD_IS_BOUGHT = 55;

const ST_PLAYER_SELL_CARD = 60;

const ST_PLAYER_DISCARD_DIE = 61;
const ST_PLAYER_DISCARD_KEEP_CARD = 62;
const ST_PLAYER_GIVE_GOLDEN_SCARAB = 63;
const ST_PLAYER_GIVE_SYMBOLS = 64;
const ST_PLAYER_SELECT_EXTRA_DIE = 65;
const ST_PLAYER_REROLL_OR_DISCARD_DICE = 66;
const ST_MULTIPLAYER_REROLL_DICE = 67;

const ST_PLAYER_TAKE_WICKEDNESS_TILE = 70;
const ST_PLAYER_CHANGE_MIMICKED_CARD_WICKEDNESS_TILE = 72;

const ST_MULTIPLAYER_ANSWER_QUESTION = 75;
const ST_AFTER_ANSWER_QUESTION = 76;

const ST_END_MINDBUG = 77;

const ST_MULTIPLAYER_BEFORE_END_TURN = 78;
const ST_AFTER_BEFORE_END_TURN = 79;
const ST_RESOLVE_END_TURN = 80;
const ST_END_TURN = 81;
const ST_NEXT_PLAYER = 90;

const ST_END_SCORE = 98;

/*
 * Interventions
 */

const CHANGE_ACTIVE_PLAYER_DIE_INTERVENTION = 'PsychicProbeIntervention'; // /!\ on rename 
const OPPORTUNIST_INTERVENTION = 'OpportunistIntervention';
const CANCEL_DAMAGE_INTERVENTION = 'CancelDamageIntervention';
const SMASHED_PLAYERS_IN_TOKYO = 'SmashedPlayersInTokyo';

/*
 * Options
 */

const PICK_MONSTER_OPTION = 100;
const AUTO_SKIP_OPTION = 110;
const TWO_PLAYERS_VARIANT_OPTION = 120;
const BONUS_MONSTERS_OPTION = 102;
const HALLOWEEN_EXPANSION_OPTION = 103;
const KINGKONG_EXPANSION_OPTION = 104;
const CYBERTOOTH_EXPANSION_OPTION = 105;
const MUTANT_EVOLUTION_VARIANT_OPTION = 106;
const CTHULHU_EXPANSION_OPTION = 107;
const ANUBIS_EXPANSION_OPTION = 108;
const WICKEDNESS_EXPANSION_OPTION = 109;
const POWERUP_EXPANSION_OPTION = 111;
const DARK_EDITION_OPTION = 112;
const ORIGINS_OPTION = 113;
const MINDBUG_EXPANSION_OPTION = 114;
const ORIGINS_EXCLUSIVE_CARDS_OPTION = 130;
const MINDBUG_CARDS_OPTION = 131;

/*
 * Variables
 */

const EXTRA_ROLLS = 'ExtraRolls';
const FREEZE_TIME_MAX_TURNS = 'FreezeTimeMaxTurns';
const FREEZE_TIME_CURRENT_TURN = 'FreezeTimeCurrentTurn';
const FRENZY_EXTRA_TURN = 'FrenzyExtraTurn';
const FINAL_PUSH_EXTRA_TURN = 'FinalPushExtraTurn';
const BUILDERS_UPRISING_EXTRA_TURN = 'BuildersUprisingExtraTurn';
const PANDA_EXPRESS_EXTRA_TURN = 'PandaExpressExtraTurn';
const JUNGLE_FRENZY_EXTRA_TURN = 'JungleFrenzyExtraTurn';
const PSYCHIC_PROBE_ROLLED_A_3 = 'PsychicProbeRolledA3';
const KILL_PLAYERS_SCORE_AUX = 'KillPlayersScoreAux';
const FRENZY_EXTRA_TURN_FOR_OPPORTUNIST = 'FrenzyExtraTurnForOpportunist';
const PLAYER_BEFORE_FRENZY_EXTRA_TURN_FOR_OPPORTUNIST = 'PlayerBeforeFrenzyExtraTurnForOpportunist';
const SKIP_BUY_PHASE = 'SkipBuyPhase';
const CLOWN_ACTIVATED = 'ClownActivated';
const CHEERLEADER_SUPPORT = 'CheerleaderSupport';
const STATE_AFTER_RESOLVE = 'stateAfterResolve';
const PLAYER_WITH_GOLDEN_SCARAB = 'PlayerWithGoldenScarab';
const RAGING_FLOOD_EXTRA_DIE = 'RagingFloodExtraDie';
const FALSE_BLESSING_USED_DIE = 'FalseBlessingUsedDie';
const DICE_NUMBER = 'DiceNumber';
const RAGING_FLOOD_EXTRA_DIE_SELECTED = 'RagingFloodExtraDieSelected';
const MUTANT_EVOLUTION_TURN = 'MutantEvolutionTurn';
const PREVENT_ENTER_TOKYO = 'PreventEnterTokyo';
const ENCASED_IN_ICE_DIE_ID = 'EncasedInIceDieId';
const TARGETED_PLAYER = 'TargetedPlayer';
const MINDBUGGED_PLAYER = 'MindbuggedPlayer';
const NEXT_POWER_CARD_COST_REDUCTION = 'NEXT_POWER_CARD_COST_REDUCTION';

/*
 * Global variables
 */

const FIRE_BREATHING_DAMAGES = 'FireBreathingDamages';
const FUNNY_LOOKING_BUT_DANGEROUS_DAMAGES = 'FunnyLookingButDangerousDamages';
const FLAMING_AURA_DAMAGES = 'FlamingAuraDamages';
const DICE_COUNTS = 'DiceCounts';
const USED_CARDS = 'UsedCards';
const JETS_DAMAGES = 'JetsDamages'; // also contains Simian Scamper damages
const MIMICKED_CARD = 'MimickedCard';
const USED_WINGS = 'UsedWings';
const MADE_IN_A_LAB = 'MadeInALab';
const BURROWING_PLAYERS = 'BurrowingPlayers';
const UNSTABLE_DNA_PLAYERS = 'UnstableDNAPlayers';
const JAGGED_TACTICIAN_PLAYERS = 'JaggedTacticianPlayers';
const QUESTION = 'Question';
const CARD_BEING_BOUGHT = 'CardBeingBought';
const STACKED_STATES = 'StackedStates';
const STARTED_TURN_IN_TOKYO = 'StartedTurnInTokyo';
const SUPERIOR_ALIEN_TECHNOLOGY_TOKENS = 'SuperiorAlienTechnologyTokens';
const ELECTRIC_CARROT_CHOICES = 'ElectricCarrotChoices';
const MINDBUGS_OVERLORD = 'MINDBUGS_OVERLORD';

/*
 * Cards
 */
// keep
const ACID_ATTACK_CARD = 1;
const ALIEN_ORIGIN_CARD = 2;
const ALPHA_MONSTER_CARD = 3;
const ARMOR_PLATING_CARD = 4;
const BACKGROUND_DWELLER_CARD = 5;
const BURROWING_CARD = 6;
const CAMOUFLAGE_CARD = 7;
const COMPLETE_DESTRUCTION_CARD = 8;
const MEDIA_FRIENDLY_CARD = 9;
const EATER_OF_THE_DEAD_CARD = 10;
const ENERGY_HOARDER_CARD = 11;
const EVEN_BIGGER_CARD = 12;
const EXTRA_HEAD_1_CARD = 13;
const EXTRA_HEAD_2_CARD = 14;
const FIRE_BREATHING_CARD = 15;
const FREEZE_TIME_CARD = 16;
const FRIEND_OF_CHILDREN_CARD = 17;
const GIANT_BRAIN_CARD = 18;
const GOURMET_CARD = 19;
const HEALING_RAY_CARD = 20;
const HERBIVORE_CARD = 21;
const HERD_CULLER_CARD = 22;
const IT_HAS_A_CHILD_CARD = 23;
const JETS_CARD = 24;
const MADE_IN_A_LAB_CARD = 25;
const METAMORPH_CARD = 26;
const MIMIC_CARD = 27;
const BATTERY_MONSTER_CARD = 28;
const NOVA_BREATH_CARD = 29;
const DETRITIVORE_CARD = 30;
const OPPORTUNIST_CARD = 31;
const PARASITIC_TENTACLES_CARD = 32;
const PLOT_TWIST_CARD = 33;
const POISON_QUILLS_CARD = 34;
const POISON_SPIT_CARD = 35;
const PSYCHIC_PROBE_CARD = 36;
const RAPID_HEALING_CARD = 37;
const REGENERATION_CARD = 38;
const ROOTING_FOR_THE_UNDERDOG_CARD = 39;
const SHRINK_RAY_CARD = 40;
const SMOKE_CLOUD_CARD = 41;
const SOLAR_POWERED_CARD = 42;
const SPIKED_TAIL_CARD = 43;
const STRETCHY_CARD = 44;
const ENERGY_DRINK_CARD = 45;
const URBAVORE_CARD = 46;
const WE_RE_ONLY_MAKING_IT_STRONGER_CARD = 47;
const WINGS_CARD = 48;
//Dark edition :
const HIBERNATION_CARD = 49;
const NANOBOTS_CARD = 50;
const NATURAL_SELECTION_CARD = 51;
const REFLECTIVE_HIDE_CARD = 52;
const SUPER_JUMP_CARD = 53;
const UNSTABLE_DNA_CARD = 54;
const ZOMBIFY_CARD = 55;
// Origins :
const BIOFUEL_CARD = 56;
const DRAINING_RAY_CARD = 57;
const ELECTRIC_ARMOR_CARD = 58;
const FLAMING_AURA_CARD = 59;
const GAMMA_BLAST_CARD = 60;
const HUNGRY_URBAVORE_CARD = 61;
const JAGGED_TACTICIAN_CARD = 62;
const ORB_OF_DOM_CARD = 63;
const SCAVENGER_CARD = 64;
const SHRINKY_CARD = 65;
const BULL_HEADED_CARD = 66;
// Mindbug :
const FREE_WILL_CARD = 67;
const EVASIVE_MINDBUG_CARD = 68;
const NO_BRAIN_CARD = 69;

// discard
const APPARTMENT_BUILDING_CARD = 101;
const COMMUTER_TRAIN_CARD = 102;
const CORNER_STORE_CARD = 103;
const DEATH_FROM_ABOVE_CARD = 104;
const ENERGIZE_CARD = 105;
const EVACUATION_ORDER_1_CARD = 106;
const EVACUATION_ORDER_2_CARD = 107;
const FLAME_THROWER_CARD = 108;
const FRENZY_CARD = 109;
const GAS_REFINERY_CARD = 110;
const HEAL_CARD = 111;
const HIGH_ALTITUDE_BOMBING_CARD = 112;
const JET_FIGHTERS_CARD = 113;
const NATIONAL_GUARD_CARD = 114;
const NUCLEAR_POWER_PLANT_CARD = 115;
const SKYSCRAPER_CARD = 116;
const TANK_CARD = 117;
const VAST_STORM_CARD = 118;
//Dark edition :
const MONSTER_PETS_CARD = 119;
// Origins :
const BARRICADES_CARD = 120;
const ICE_CREAM_TRUCK_CARD = 121;
const SUPERTOWER_CARD = 122;
// Mindbug :
const MINDBUG_CARD = 123;
const DYSFUNCTIONAL_MINDBUG_CARD = 124;
const TREASURE_CARD = 125;
const MIRACULOUS_MINDBUG_CARD = 126;

// costume
const ASTRONAUT_CARD = 201;
const GHOST_CARD = 202;
const VAMPIRE_CARD = 203;
const WITCH_CARD = 204;
const DEVIL_CARD = 205;
const PIRATE_CARD = 206;
const PRINCESS_CARD = 207;
const ZOMBIE_CARD = 208;
const CHEERLEADER_CARD = 209;
const ROBOT_CARD = 210;
const STATUE_OF_LIBERTY_CARD = 211;
const CLOWN_CARD = 212;

// transformation
const FORM_CARD = 301;

// consumable
const OVEREQUIPPED_TRAPPER_CARD = 401;
const LEGENDARY_HUNTER_CARD = 402;
const UNRELIABLE_TARGETING_CARD = 403;
const SNEAKY_ALLOY_CARD = 404;
const OFFENSIVE_PROTOCOL_CARD = 405;
const ARCANE_SCEPTER_CARD = 406;
const ENERGY_ARMOR_CARD = 407;
const STRANGE_DESIGN_CARD = 408;
const ANCESTRAL_DEFENSE_CARD = 409;
const TOXIC_PETALS_CARD = 410;
const EXPLOSIVE_CRYSTALS_CARD = 411;
const ELECTRO_WHIP_CARD = 412;
const BOLD_MANEUVER_CARD = 413;
const UNFAIR_GIFT_CARD = 414;
const MAXIMUM_EFFORT_CARD = 415;
const DEADLY_SHELL_CARD = 416;
const SPATIAL_HUNTER_CARD = 417;

// curse cards
const PHARAONIC_EGO_CURSE_CARD = 1;
const ISIS_S_DISGRACE_CURSE_CARD = 2;
const THOT_S_BLINDNESS_CURSE_CARD = 3;
const TUTANKHAMUN_S_CURSE_CURSE_CARD = 4;
const BURIED_IN_SAND_CURSE_CARD = 5;
const RAGING_FLOOD_CURSE_CARD = 6;
const HOTEP_S_PEACE_CURSE_CARD = 7;
const SET_S_STORM_CURSE_CARD = 8;
const BUILDERS_UPRISING_CURSE_CARD = 9;
const INADEQUATE_OFFERING_CURSE_CARD = 10;
const BOW_BEFORE_RA_CURSE_CARD = 11;
const VENGEANCE_OF_HORUS_CURSE_CARD = 12;
const ORDEAL_OF_THE_MIGHTY_CURSE_CARD = 13;
const ORDEAL_OF_THE_WEALTHY_CURSE_CARD = 14;
const ORDEAL_OF_THE_SPIRITUAL_CURSE_CARD = 15;
const RESURRECTION_OF_OSIRIS_CURSE_CARD = 16;
const FORBIDDEN_LIBRARY_CURSE_CARD = 17;
const CONFUSED_SENSES_CURSE_CARD = 18;
const PHARAONIC_SKIN_CURSE_CARD = 19;
const KHEPRI_S_REBELLION_CURSE_CARD = 20;
const BODY_SPIRIT_AND_KA_CURSE_CARD = 21;
const FALSE_BLESSING_CURSE_CARD = 22;
const GAZE_OF_THE_SPHINX_CURSE_CARD = 23;
const SCRIBE_S_PERSEVERANCE_CURSE_CARD = 24;

// evolutions : Space Penguin
const FREEZE_RAY_EVOLUTION = 11;
const MIRACULOUS_CATCH_EVOLUTION = 12;
const DEEP_DIVE_EVOLUTION = 13;
const COLD_WAVE_EVOLUTION = 14;
const ENCASED_IN_ICE_EVOLUTION = 15;
const BLIZZARD_EVOLUTION = 16;
const BLACK_DIAMOND_EVOLUTION = 17;
const ICY_REFLECTION_EVOLUTION = 18;
// evolutions : Alienoid
const ALIEN_SCOURGE_EVOLUTION = 21;
const PRECISION_FIELD_SUPPORT_EVOLUTION = 22;
const ANGER_BATTERIES_EVOLUTION = 23;
const ADAPTING_TECHNOLOGY_EVOLUTION = 24;
const FUNNY_LOOKING_BUT_DANGEROUS_EVOLUTION = 25;
const EXOTIC_ARMS_EVOLUTION = 26;
const MOTHERSHIP_SUPPORT_EVOLUTION = 27;
const SUPERIOR_ALIEN_TECHNOLOGY_EVOLUTION = 28;
// evolutions : Cyber Kitty
const NINE_LIVES_EVOLUTION = 31;
const MEGA_PURR_EVOLUTION = 32;
const ELECTRO_SCRATCH_EVOLUTION = 33;
const CAT_NIP_EVOLUTION = 34;
const PLAY_WITH_YOUR_FOOD_EVOLUTION = 35;
const FELINE_MOTOR_EVOLUTION = 36;
const MOUSE_HUNTER_EVOLUTION = 37;
const MEOW_MISSLE_EVOLUTION = 38;
// evolutions : The King
const MONKEY_RUSH_EVOLUTION = 41;
const SIMIAN_SCAMPER_EVOLUTION = 42;
const JUNGLE_FRENZY_EVOLUTION = 43;
const GIANT_BANANA_EVOLUTION = 44;
const CHEST_THUMPING_EVOLUTION = 45;
const ALPHA_MALE_EVOLUTION = 46;
const I_AM_THE_KING_EVOLUTION = 47;
const TWAS_BEAUTY_KILLED_THE_BEAST_EVOLUTION = 48;
// evolutions : Gigazaur
const DETACHABLE_TAIL_EVOLUTION = 51;
const RADIOACTIVE_WASTE_EVOLUTION = 52;
const PRIMAL_BELLOW_EVOLUTION = 53;
const SAURIAN_ADAPTABILITY_EVOLUTION = 54;
const DEFENDER_OF_TOKYO_EVOLUTION = 55;
const HEAT_VISION_EVOLUTION = 56;
const GAMMA_BREATH_EVOLUTION = 57;
const TAIL_SWEEP_EVOLUTION = 58;
// evolutions : Meka Dragon
const MECHA_BLAST_EVOLUTION = 61;
const DESTRUCTIVE_ANALYSIS_EVOLUTION = 62;
const PROGRAMMED_TO_DESTROY_EVOLUTION = 63;
const TUNE_UP_EVOLUTION = 64;
const BREATH_OF_DOOM_EVOLUTION = 65;
const LIGHTNING_ARMOR_EVOLUTION = 66;
const CLAWS_OF_STEEL_EVOLUTION = 67;
const TARGET_ACQUIRED_EVOLUTION = 68;
// evolutions : Boogie Woogie
const BOO_EVOLUTION = 71;
const WORST_NIGHTMARE_EVOLUTION = 72;
const I_LIVE_UNDER_YOUR_BED_EVOLUTION = 73;
const BOOGIE_DANCE_EVOLUTION = 74;
const WELL_OF_SHADOW_EVOLUTION = 75;
const WORM_INVADERS_EVOLUTION = 76;
const NIGHTLIFE_EVOLUTION = 77;
const DUSK_RITUAL_EVOLUTION = 78;
// evolutions : Pumpkin Jack
const DETACHABLE_HEAD_EVOLUTION = 81;
const IGNIS_FATUS_EVOLUTION = 82;
const SMASHING_PUMPKIN_EVOLUTION = 83;
const TRICK_OR_THREAT_EVOLUTION = 84;
const BOBBING_FOR_APPLES_EVOLUTION = 85;
const FEAST_OF_CROWS_EVOLUTION = 86;
const SCYTHE_EVOLUTION = 87;
const CANDY_EVOLUTION = 88;
// evolutions : King Kong
const SON_OF_KONG_KIKO_EVOLUTION = 111;
const KING_OF_SKULL_ISLAND_EVOLUTION = 112; // TODOPUKK : Play when you Yield Tokyo. Gain [Health] to your maximum amount. Skip your next turn.
const ISLANDER_SACRIFICE_EVOLUTION = 113; // TODOPUKK : Roll 6 dice. Gain 1 [Energy] per [Lightning] and 1 [Health] per [Heart] rolled (even if you are in Tokyo). If you rolled less than 2 [Lightning] and/or [Heart], take this card back.
const MONKEY_LEAP_EVOLUTION = 114; // TODOPUKK : Play during another Monster's movement phase. If Tokyo is empty, you can take control of it instead of the Monster whose turn it is.
const IT_WAS_BEAUTY_KILLED_THE_BEAST_EVOLUTION = 115; // TODOPUKK : Take the Beauty card, [King Kong] side up. If you don't have the Beauty card at the start of your turn, you cannot reroll [Claw] and you wound only the Monster with the Beauty card.
const JET_CLUB_EVOLUTION = 116;
const EIGHTH_WONDER_OF_THE_WORLD_EVOLUTION = 117;
const CLIMB_TOKYO_TOWER_EVOLUTION = 118;
// evolutions : Pandakaï
const PANDA_MONIUM_EVOLUTION = 131;
const EATS_SHOOTS_AND_LEAVES_EVOLUTION = 132;
const BAMBOOZLE_EVOLUTION = 133;
const BEAR_NECESSITIES_EVOLUTION = 134;
const PANDA_EXPRESS_EVOLUTION = 135;
const BAMBOO_SUPPLY_EVOLUTION = 136;
const PANDARWINISM_EVOLUTION = 137;
const YIN_YANG_EVOLUTION = 138;
// evolutions : Cyber Bunny
const STROKE_OF_GENIUS_EVOLUTION = 141;
const EMERGENCY_BATTERY_EVOLUTION = 142;
const RABBIT_S_FOOT_EVOLUTION = 143;
const HEART_OF_THE_RABBIT_EVOLUTION = 144;
const SECRET_LABORATORY_EVOLUTION = 145;
const KING_OF_THE_GIZMO_EVOLUTION = 146;
const ENERGY_SWORD_EVOLUTION = 147;
const ELECTRIC_CARROT_EVOLUTION = 148;
// evolutions : Kraken
const HEALING_RAIN_EVOLUTION = 151;
const DESTRUCTIVE_WAVE_EVOLUTION = 152;
const CULT_WORSHIPPERS_EVOLUTION = 153;
const HIGH_TIDE_EVOLUTION = 154;
const TERROR_OF_THE_DEEP_EVOLUTION = 155;
const EATER_OF_SOULS_EVOLUTION = 156;
const SUNKEN_TEMPLE_EVOLUTION = 157;
const MANDIBLES_OF_DREAD_EVOLUTION = 158;
// evolutions : Baby Gigazaur
const MY_TOY_EVOLUTION = 181;
const GROWING_FAST_EVOLUTION = 182;
const NURTURE_THE_YOUNG_EVOLUTION = 183;
const TINY_TAIL_EVOLUTION = 184;
const TOO_CUTE_TO_SMASH_EVOLUTION = 185;
const SO_SMALL_EVOLUTION = 186;
const UNDERRATED_EVOLUTION = 187;
const YUMMY_YUMMY_EVOLUTION = 188;
// evolutions : Gigasnail Hydra
const UNSTOPPABLE_HYDRA_EVOLUTION_1 = 611;
const UNSTOPPABLE_HYDRA_EVOLUTION_2 = 612;
const ENERGY_INFUSED_MONSTER_EVOLUTION = 613;
const THREE_TIMES_AS_STURDY_EVOLUTION = 614;
const SCARY_FACE_EVOLUTION = 615;
const THREE_TIMES_AS_STRONG_EVOLUTION = 616;
const THINKING_FACE_EVOLUTION = 617;
const HUNGRY_FACE_EVOLUTION = 618;
// evolutions : MasterMindbug
const MINDBUG_ACQUISITION_EVOLUTION = 621;
const INTERGALACTIC_GENIUS_EVOLUTION = 622;
const SUPERIOR_BRAIN_EVOLUTION = 623;
const INTERDIMENSIONAL_PORTAL_EVOLUTION = 624;
const HELPFUL_MINDBUG_EVOLUTION = 625;
const MINDBUGS_OVERLORD_EVOLUTION = 626;
const MIND_CONTROL_EVOLUTION = 627;
const NEUTRALIZING_LOOK_EVOLUTION = 628;
// evolutions : Sharky Crab-dog Mummypus-Zilla
const SHARK_ATTACK_EVOLUTION = 631;
const ENERGY_DEVOURER_EVOLUTION = 632;
const STRANGE_EVOLUTION_EVOLUTION = 633;
const CRAB_CLAW_EVOLUTION = 634;
const UNDEAD_MUMMY_EVOLUTION = 635;
const FOLLOW_THE_CUBES_EVOLUTION = 636;
const POISONED_TENTACLES_EVOLUTION = 637;
const CHEW_PINCH_CATCH_AND_SMACK_EVOLUTION = 638;

?>
